server:
  port: 8080
  shutdown: graceful
application:
  context-path: /pagamento-simplificado/api
spring:
  application:
    name: pagamento-simplificado
  profiles:
    active: local
management:
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true
  endpoints:
    web:
      exposure:
        include: health, shutdown
  endpoint:
    shutdown:
      enabled: true
    health:
      probes.enabled: true